### ISSUE TITLE
500 error after PATCH Bios/Settings

### ISSUE THREAD

**Issue by ehaligow** [ODIM-Project/BMCSimulator#2]
Sending PATCH to Bios/Settings gives Internal ServerError:
```
intel@ubuntu:~$ curl -X PATCH -k -u 'admin:admin' https://bmcsim:55555/redfish/v1/Systems/1/Bios/Settings -d '{"Attributes": {"QuietBoot": 2}}' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   186  100   154  100    32   4666    969 --:--:-- --:--:-- --:--:--  5636
{
  "title": "Internal server error",
  "status": 500,
  "type": "https://javalin.io/documentation#internalservererrorresponse",
  "details": []
}
```

When we skip "Attributes" from json, the PATCH will be send correctly.

Here is the instruction how the PATCH on Bios/Settings should look like:
https://github.com/ODIM-Project/ODIM/tree/main/svc-systems#changing-bios-settings

**Comment by ArturBaryla** [comment]
Can you put some logs? I think it can be a problem with embeddedObject

**Comment by ehaligow** [comment]
`10:40:57.253 [qtp844194537-15] INFO  c.odim.simulator.http.ServerProvider - E.H. Before creating request PATCH at https://bmcsim:55555/redfish/v1/Systems/1/Bios/Settings
10:40:57.255 [qtp844194537-15] INFO  c.odim.simulator.http.ServerProvider - E.H. After creating request, before response
10:40:57.259 [qtp844194537-15] WARN  io.javalin.Javalin - Uncaught exception
java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: UNKNOWN; line: -1, column: -1]
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4314)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4245)
        at com.odim.utils.ObjectNodeKt.getString(ObjectNode.kt:53)
        at com.odim.simulator.repo.bmc.behaviors.PatchOnBiosSettings.run(PatchOnBiosSettings.kt:35)
        at com.odim.simulator.behaviors.ResourceBehaviors.applyBehaviors(ResourceBehaviors.kt:157)
        at com.odim.simulator.behaviors.ResourceBehaviors.createResponse(ResourceBehaviors.kt:151)
        at com.odim.simulator.execution.Executor$run$job$1.invoke(Executor.kt:68)
        at com.odim.simulator.execution.Executor$run$job$1.invoke(Executor.kt:50)
        at com.odim.simulator.execution.Executor.doSync(Executor.kt:128)
        at com.odim.simulator.execution.Executor.run(Executor.kt:71)
        at com.odim.simulator.RedfishSimulator.createResponse(Simulator.kt:110)
        at com.odim.simulator.RedfishSimulator.findResource(Simulator.kt:134)
        at com.odim.simulator.RedfishSimulator.createResponse(Simulator.kt:118)
        at com.odim.simulator.http.ServerProvider.createResponse(ServerProvider.kt:134)
        at com.odim.simulator.http.ServerProvider.getRequestHandler(ServerProvider.kt:120)
        at com.odim.simulator.http.ServerProvider.access$getRequestHandler(ServerProvider.kt:43)
        at com.odim.simulator.http.ServerProvider$serve$$inlined$with$lambda$4.handle(ServerProvider.kt:69)
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
        at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
        at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
        at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: UNKNOWN; line: -1, column: -1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280)
        at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:872)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4309)
        ... 54 common frames omitted
10:41:13.474 [qtp844194537-17] INFO  c.odim.simulator.http.ServerProvider - E.H. Before creating request PATCH at https://bmcsim:55555/redfish/v1/Systems/1/Bios/Settings
10:41:13.475 [qtp844194537-17] INFO  c.odim.simulator.http.ServerProvider - E.H. After creating request, before response`
